services:
    app:
      container_name: app
      build:
        dockerfile: Dockerfile
      command:
        - "python"
        - "run_main.py"
      restart: always
      ports:
        - "8000:8000"

    db:
      image: postgres:16.2
      container_name: db
      restart: always
      env_file:
        - .env.docker
      ports:
        - "5432:5432"
      volumes:
        - db:/var/lib/postgresql/data

    redis:
      container_name: redis
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"

volumes:
  db:
    driver: local
